export const rows = [
  {
    Id: 1,
    RegisterId: "2135",
    Name: "Bassam",
    Email: "b7said@gmail.com",
    age: "25",
    Address: "mahkma",
    City: "Delingate",
  },
  {
    Id: 2,
    RegisterId: "365",
    Name: "said",
    Email: "b10@gmail.com",
    age: "20",
    Address: "komhamada",
    City: "Damnhour",
  },
  {
    Id: 3,
    RegisterId: "3655",
    Name: "Mohamed",
    Email: "mohamed@gmail.com",
    age: "30",
    Address: "mohafza",
    City: "Damnhour",
  },
  {
    Id: 4,
    RegisterId: "9835",
    RegisterId: "21",
    Name: "Abdo",
    Email: "Abdo@gmail.com",
    age: "42",
    Address: "mohafza",
    City: "Damnhour",
  },
  {
    Id: 5,
    RegisterId: "26987",
    Name: "Yousef",
    Email: "yousef@gmail.com",
    age: "30",
    Address: "nozha",
    City: "Damnhour",
  },
  {
    Id: 6,
    RegisterId: "69854",
    Name: "Mahmoud",
    Email: "mahmoud@gmail.com",
    age: "25",
    Address: "geza",
    City: "cairo",
  },
  {
    Id: 7,
    RegisterId: "98535",
    Name: "Mahmoud",
    Email: "mahmoud@gmail.com",
    age: "25",
    Address: "mohafza",
    City: "Damnhour",
  },
  {
    Id: 8,
    RegisterId: "3589",
    Name: "Ahmed",
    Email: "mahmoud@gmail.com",
    age: "25",
    Address: "45sterret",
    City: "Alex",
  },
  {
    Id: 9,
    RegisterId: "25695",
    Name: "Mostafa",
    Email: "mostafa@gmail.com",
    age: "25",
    Address: "mahkma",
    City: "Delingate",
  },
  {
    Id: 10,
    RegisterId: "2535",
    Name: "Mahmoud",
    Email: "mahmoud@gmail.com",
    age: "25",
    Address: "mohafza",
    City: "Damnhour",
  },
];
 export const columns = [
   { field: "Id", headerName: "ID", width:33,align:"center",headerAlign:"center" },
   { field: "RegisterId", headerName: "RegisterId", flex:1,align:"center",headerAlign:"center" },
   { field: "Name", headerName: "Name", flex:1 ,align:"center",headerAlign:"center"},
   { field: "Email", headerName: "Email", flex:1,align:"center",headerAlign:"center" },
   { field: "age", headerName: "Age", flex:1 ,align:"center",headerAlign:"center"},
   { field: "Address", headerName: "Address", flex:1,align:"center",headerAlign:"center" },
   { field: "City", headerName: "City", flex:1,align:"center",headerAlign:"center" },
 ];